### ISSUE TITLE
Issue while using

### ISSUE THREAD

**Issue by bhoomika27** [typicode/demo#397]
Its throwing 404 for me I have created .https://jsonplaceholder.typicode.com/bhoomika27/todoData
Please suggest what to do with this?

**Comment by typicode** [comment]
Hi @bhoomika27,

You would need to use https://my-json-server.typicode.com/bhoomika27/todoData.

That said `db.json` is too big for the Open Source plan. You can either reduce its size or get a Sponsor plan ([plans](https://my-json-server.typicode.com/pricing))

**Comment by bhoomika27** [comment]
Thanks Its solved
