### ISSUE TITLE
Gettimg 404 Error Code

### ISSUE THREAD

**Issue by joe-mallaya** [typicode/demo#685]
I created db.json and try to check whether it works but i am getting error as -> "GET https://my-json-server.typicode.com/mallia-pk/alpha/db.json 404"

my db.json file is in: https://github.com/mallia-pk/alpha

**Comment by ghost** [comment]
use this link
https://my-json-server.typicode.com/mallia-pk/alpha/Member/
and this thi get item 1
https://my-json-server.typicode.com/mallia-pk/alpha/Member/1
